name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    strategy:
      matrix:
        rvm: ["3.0", "3.1", "3.2", "ruby-head"]
        rack: ["3.0.7", "main"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment Variables
        run: |
          echo "RACK=${RACK}" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
