name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    strategy:
      matrix:
        rvm: ["3.0", "3.1", "3.2", "3.3", "ruby-head"]
        rack: ["3-0-stable"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Environment Variables
        run: |
          echo "RACK=${{ matrix.rack }}" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
